# Generated by Django 3.2.9 on 2021-12-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='name',
        ),
    ]
