name: Coverage test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install poetry
          python -m pip install --upgrade pip
          poetry update
          make install

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: sqlite:///task_manager.sqlite3
          ENVIRONMENT: Github_actions
          DEBUG: "True"
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make coverage
          debug: true